import os
from jinja2 import Environment, FileSystemLoader
from playwright.async_api import async_playwright
import base64

def get_base64_image(image_path):
    """Convert local image to base64 string."""
    if os.path.exists(image_path):
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode('utf-8')
    return ""

async def generate_intelligence_report(data: dict):
    """
    Takes the combined API response and generates a PDF in memory.
    """
    task_id = data.get("task_id", "unknown_task")
    logo_path = os.path.join(os.getcwd(), "assets", "logo.png")
    logo_b64 = get_base64_image(logo_path)
    # Setup Jinja2
    # Ensure you have a folder named 'templates' with report.html inside
    template_dir = os.path.join(os.getcwd(), "templates")
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("report.html")

    # Render HTML string
    # We pass the entire dictionary returned by your API
    html_content = template.render(
        task_id=task_id,
        satellite=data.get("satellite_analytics", {}),
        logo_base64=logo_b64,
        location=data.get("location_details", {}),
        weather_data=data.get("weather_data", {}),
        generated_at=data.get("metadata", {}).get("timestamp", "")
    )

    # Use Playwright to convert HTML to PDF
    async with async_playwright() as p:
        # Launch headless browser
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        
        # Set content directly from memory (Fast!)
        await page.set_content(html_content)
        
        # Wait for all Base64 images to render
        await page.wait_for_load_state("networkidle")

        pdf_path = f"data/{task_id}/intelligence_report.pdf"
        os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

        # Print to PDF with A4 settings
        # Inside pdf_generator.py
        await page.pdf(
            path=pdf_path,
            format="A4",
            print_background=True,
            display_header_footer=True, # Enable headers/footers
            footer_template=f"""
                <div style="font-size: 10px; width: 100%; margin: 0 40px; border-top: 1px solid #ddd; padding-top: 5px; display: flex; justify-content: space-between; color: #7f8c8d; font-family: 'Segoe UI', sans-serif;">
                    <span>Generated by <i>TerraDrishti Agriculture Dashboard</i></span>
                    <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
                    <span>Report ID - <b>{task_id}</b></span>
                </div>
            """,
            margin={
                "top": "1cm",
                "bottom": "3cm", # Ensure enough room for the footer template
                "left": "1cm",
                "right": "1cm"
            }
        )
        
        await browser.close()
        return pdf_path